// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/configuration.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// HashingAlgorithm is encoded into the configuration transaction as a
// configuration item of type Chain with a Key of "HashingAlgorithm" and a
// Value of HashingAlgorithm as marshaled protobuf bytes
type HashingAlgorithm struct {
	// SHA256 is currently the only supported and tested algorithm.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashingAlgorithm) Reset()         { *m = HashingAlgorithm{} }
func (m *HashingAlgorithm) String() string { return proto.CompactTextString(m) }
func (*HashingAlgorithm) ProtoMessage()    {}
func (*HashingAlgorithm) Descriptor() ([]byte, []int) {
	return fileDescriptor_cba1ec2883858369, []int{0}
}

func (m *HashingAlgorithm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashingAlgorithm.Unmarshal(m, b)
}
func (m *HashingAlgorithm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashingAlgorithm.Marshal(b, m, deterministic)
}
func (m *HashingAlgorithm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashingAlgorithm.Merge(m, src)
}
func (m *HashingAlgorithm) XXX_Size() int {
	return xxx_messageInfo_HashingAlgorithm.Size(m)
}
func (m *HashingAlgorithm) XXX_DiscardUnknown() {
	xxx_messageInfo_HashingAlgorithm.DiscardUnknown(m)
}

var xxx_messageInfo_HashingAlgorithm proto.InternalMessageInfo

func (m *HashingAlgorithm) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// BlockDataHashingStructure is encoded into the configuration transaction as a configuration item of
// type Chain with a Key of "BlockDataHashingStructure" and a Value of HashingAlgorithm as marshaled protobuf bytes
type BlockDataHashingStructure struct {
	// width specifies the width of the Merkle tree to use when computing the BlockDataHash
	// in order to replicate flat hashing, set this width to MAX_UINT32
	Width                uint32   `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockDataHashingStructure) Reset()         { *m = BlockDataHashingStructure{} }
func (m *BlockDataHashingStructure) String() string { return proto.CompactTextString(m) }
func (*BlockDataHashingStructure) ProtoMessage()    {}
func (*BlockDataHashingStructure) Descriptor() ([]byte, []int) {
	return fileDescriptor_cba1ec2883858369, []int{1}
}

func (m *BlockDataHashingStructure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockDataHashingStructure.Unmarshal(m, b)
}
func (m *BlockDataHashingStructure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockDataHashingStructure.Marshal(b, m, deterministic)
}
func (m *BlockDataHashingStructure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockDataHashingStructure.Merge(m, src)
}
func (m *BlockDataHashingStructure) XXX_Size() int {
	return xxx_messageInfo_BlockDataHashingStructure.Size(m)
}
func (m *BlockDataHashingStructure) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockDataHashingStructure.DiscardUnknown(m)
}

var xxx_messageInfo_BlockDataHashingStructure proto.InternalMessageInfo

func (m *BlockDataHashingStructure) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

// OrdererAddresses is encoded into the configuration transaction as a configuration item of type Chain
// with a Key of "OrdererAddresses" and a Value of OrdererAddresses as marshaled protobuf bytes
type OrdererAddresses struct {
	Addresses            []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrdererAddresses) Reset()         { *m = OrdererAddresses{} }
func (m *OrdererAddresses) String() string { return proto.CompactTextString(m) }
func (*OrdererAddresses) ProtoMessage()    {}
func (*OrdererAddresses) Descriptor() ([]byte, []int) {
	return fileDescriptor_cba1ec2883858369, []int{2}
}

func (m *OrdererAddresses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrdererAddresses.Unmarshal(m, b)
}
func (m *OrdererAddresses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrdererAddresses.Marshal(b, m, deterministic)
}
func (m *OrdererAddresses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrdererAddresses.Merge(m, src)
}
func (m *OrdererAddresses) XXX_Size() int {
	return xxx_messageInfo_OrdererAddresses.Size(m)
}
func (m *OrdererAddresses) XXX_DiscardUnknown() {
	xxx_messageInfo_OrdererAddresses.DiscardUnknown(m)
}

var xxx_messageInfo_OrdererAddresses proto.InternalMessageInfo

func (m *OrdererAddresses) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

// Consenter represents a consenting node (i.e. replica).
type Consenter struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	MspId                string   `protobuf:"bytes,4,opt,name=msp_id,json=mspId,proto3" json:"msp_id,omitempty"`
	Identity             []byte   `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	ClientTlsCert        []byte   `protobuf:"bytes,6,opt,name=client_tls_cert,json=clientTlsCert,proto3" json:"client_tls_cert,omitempty"`
	ServerTlsCert        []byte   `protobuf:"bytes,7,opt,name=server_tls_cert,json=serverTlsCert,proto3" json:"server_tls_cert,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consenter) Reset()         { *m = Consenter{} }
func (m *Consenter) String() string { return proto.CompactTextString(m) }
func (*Consenter) ProtoMessage()    {}
func (*Consenter) Descriptor() ([]byte, []int) {
	return fileDescriptor_cba1ec2883858369, []int{3}
}

func (m *Consenter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consenter.Unmarshal(m, b)
}
func (m *Consenter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consenter.Marshal(b, m, deterministic)
}
func (m *Consenter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consenter.Merge(m, src)
}
func (m *Consenter) XXX_Size() int {
	return xxx_messageInfo_Consenter.Size(m)
}
func (m *Consenter) XXX_DiscardUnknown() {
	xxx_messageInfo_Consenter.DiscardUnknown(m)
}

var xxx_messageInfo_Consenter proto.InternalMessageInfo

func (m *Consenter) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Consenter) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Consenter) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Consenter) GetMspId() string {
	if m != nil {
		return m.MspId
	}
	return ""
}

func (m *Consenter) GetIdentity() []byte {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *Consenter) GetClientTlsCert() []byte {
	if m != nil {
		return m.ClientTlsCert
	}
	return nil
}

func (m *Consenter) GetServerTlsCert() []byte {
	if m != nil {
		return m.ServerTlsCert
	}
	return nil
}

// Orderers is encoded into the configuration transaction as a configuration item of type Chain
// with a Key of "Orderers" and a Value of Orderers as marshaled protobuf bytes
type Orderers struct {
	ConsenterMapping     []*Consenter `protobuf:"bytes,1,rep,name=consenter_mapping,json=consenterMapping,proto3" json:"consenter_mapping,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Orderers) Reset()         { *m = Orderers{} }
func (m *Orderers) String() string { return proto.CompactTextString(m) }
func (*Orderers) ProtoMessage()    {}
func (*Orderers) Descriptor() ([]byte, []int) {
	return fileDescriptor_cba1ec2883858369, []int{4}
}

func (m *Orderers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Orderers.Unmarshal(m, b)
}
func (m *Orderers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Orderers.Marshal(b, m, deterministic)
}
func (m *Orderers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Orderers.Merge(m, src)
}
func (m *Orderers) XXX_Size() int {
	return xxx_messageInfo_Orderers.Size(m)
}
func (m *Orderers) XXX_DiscardUnknown() {
	xxx_messageInfo_Orderers.DiscardUnknown(m)
}

var xxx_messageInfo_Orderers proto.InternalMessageInfo

func (m *Orderers) GetConsenterMapping() []*Consenter {
	if m != nil {
		return m.ConsenterMapping
	}
	return nil
}

// Consortium represents the consortium context in which the channel was created
type Consortium struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consortium) Reset()         { *m = Consortium{} }
func (m *Consortium) String() string { return proto.CompactTextString(m) }
func (*Consortium) ProtoMessage()    {}
func (*Consortium) Descriptor() ([]byte, []int) {
	return fileDescriptor_cba1ec2883858369, []int{5}
}

func (m *Consortium) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consortium.Unmarshal(m, b)
}
func (m *Consortium) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consortium.Marshal(b, m, deterministic)
}
func (m *Consortium) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consortium.Merge(m, src)
}
func (m *Consortium) XXX_Size() int {
	return xxx_messageInfo_Consortium.Size(m)
}
func (m *Consortium) XXX_DiscardUnknown() {
	xxx_messageInfo_Consortium.DiscardUnknown(m)
}

var xxx_messageInfo_Consortium proto.InternalMessageInfo

func (m *Consortium) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Capabilities message defines the capabilities a particular binary must implement
// for that binary to be able to safely participate in the channel.  The capabilities
// message is defined at the /Channel level, the /Channel/Application level, and the
// /Channel/Orderer level.
//
// The /Channel level capabilties define capabilities which both the orderer and peer
// binaries must satisfy.  These capabilties might be things like a new MSP type,
// or a new policy type.
//
// The /Channel/Orderer level capabilties define capabilities which must be supported
// by the orderer, but which have no bearing on the behavior of the peer.  For instance
// if the orderer changes the logic for how it constructs new channels, only all orderers
// must agree on the new logic.  The peers do not need to be aware of this change as
// they only interact with the channel after it has been constructed.
//
// Finally, the /Channel/Application level capabilities define capabilities which the peer
// binary must satisfy, but which have no bearing on the orderer.  For instance, if the
// peer adds a new UTXO transaction type, or changes the chaincode lifecycle requirements,
// all peers must agree on the new logic.  However, orderers never inspect transactions
// this deeply, and therefore have no need to be aware of the change.
//
// The capabilities strings defined in these messages typically correspond to release
// binary versions (e.g. "V1.1"), and are used primarilly as a mechanism for a fully
// upgraded network to switch from one set of logic to a new one.
//
// Although for V1.1, the orderers must be upgraded to V1.1 prior to the rest of the
// network, going forward, because of the split between the /Channel, /Channel/Orderer
// and /Channel/Application capabilities.  It should be possible for the orderer and
// application networks to upgrade themselves independently (with the exception of any
// new capabilities defined at the /Channel level).
type Capabilities struct {
	Capabilities         map[string]*Capability `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Capabilities) Reset()         { *m = Capabilities{} }
func (m *Capabilities) String() string { return proto.CompactTextString(m) }
func (*Capabilities) ProtoMessage()    {}
func (*Capabilities) Descriptor() ([]byte, []int) {
	return fileDescriptor_cba1ec2883858369, []int{6}
}

func (m *Capabilities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capabilities.Unmarshal(m, b)
}
func (m *Capabilities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capabilities.Marshal(b, m, deterministic)
}
func (m *Capabilities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capabilities.Merge(m, src)
}
func (m *Capabilities) XXX_Size() int {
	return xxx_messageInfo_Capabilities.Size(m)
}
func (m *Capabilities) XXX_DiscardUnknown() {
	xxx_messageInfo_Capabilities.DiscardUnknown(m)
}

var xxx_messageInfo_Capabilities proto.InternalMessageInfo

func (m *Capabilities) GetCapabilities() map[string]*Capability {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

// Capability is an empty message for the time being.  It is defined as a protobuf
// message rather than a constant, so that we may extend capabilities with other fields
// if the need arises in the future.  For the time being, a capability being in the
// capabilities map requires that that capability be supported.
type Capability struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Capability) Reset()         { *m = Capability{} }
func (m *Capability) String() string { return proto.CompactTextString(m) }
func (*Capability) ProtoMessage()    {}
func (*Capability) Descriptor() ([]byte, []int) {
	return fileDescriptor_cba1ec2883858369, []int{7}
}

func (m *Capability) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Capability.Unmarshal(m, b)
}
func (m *Capability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Capability.Marshal(b, m, deterministic)
}
func (m *Capability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Capability.Merge(m, src)
}
func (m *Capability) XXX_Size() int {
	return xxx_messageInfo_Capability.Size(m)
}
func (m *Capability) XXX_DiscardUnknown() {
	xxx_messageInfo_Capability.DiscardUnknown(m)
}

var xxx_messageInfo_Capability proto.InternalMessageInfo

type AttestationCheckingParameters struct {
	EnableChecking           bool     `protobuf:"varint,1,opt,name=enableChecking,proto3" json:"enableChecking,omitempty"`
	RequiredNumberOfMessages uint32   `protobuf:"varint,2,opt,name=requiredNumberOfMessages,proto3" json:"requiredNumberOfMessages,omitempty"`
	Frequency                uint32   `protobuf:"varint,3,opt,name=frequency,proto3" json:"frequency,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *AttestationCheckingParameters) Reset()         { *m = AttestationCheckingParameters{} }
func (m *AttestationCheckingParameters) String() string { return proto.CompactTextString(m) }
func (*AttestationCheckingParameters) ProtoMessage()    {}
func (*AttestationCheckingParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_cba1ec2883858369, []int{8}
}

func (m *AttestationCheckingParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttestationCheckingParameters.Unmarshal(m, b)
}
func (m *AttestationCheckingParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttestationCheckingParameters.Marshal(b, m, deterministic)
}
func (m *AttestationCheckingParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttestationCheckingParameters.Merge(m, src)
}
func (m *AttestationCheckingParameters) XXX_Size() int {
	return xxx_messageInfo_AttestationCheckingParameters.Size(m)
}
func (m *AttestationCheckingParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_AttestationCheckingParameters.DiscardUnknown(m)
}

var xxx_messageInfo_AttestationCheckingParameters proto.InternalMessageInfo

func (m *AttestationCheckingParameters) GetEnableChecking() bool {
	if m != nil {
		return m.EnableChecking
	}
	return false
}

func (m *AttestationCheckingParameters) GetRequiredNumberOfMessages() uint32 {
	if m != nil {
		return m.RequiredNumberOfMessages
	}
	return 0
}

func (m *AttestationCheckingParameters) GetFrequency() uint32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func init() {
	proto.RegisterType((*HashingAlgorithm)(nil), "common.HashingAlgorithm")
	proto.RegisterType((*BlockDataHashingStructure)(nil), "common.BlockDataHashingStructure")
	proto.RegisterType((*OrdererAddresses)(nil), "common.OrdererAddresses")
	proto.RegisterType((*Consenter)(nil), "common.Consenter")
	proto.RegisterType((*Orderers)(nil), "common.Orderers")
	proto.RegisterType((*Consortium)(nil), "common.Consortium")
	proto.RegisterType((*Capabilities)(nil), "common.Capabilities")
	proto.RegisterMapType((map[string]*Capability)(nil), "common.Capabilities.CapabilitiesEntry")
	proto.RegisterType((*Capability)(nil), "common.Capability")
	proto.RegisterType((*AttestationCheckingParameters)(nil), "common.AttestationCheckingParameters")
}

func init() { proto.RegisterFile("common/configuration.proto", fileDescriptor_cba1ec2883858369) }

var fileDescriptor_cba1ec2883858369 = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xc1, 0x6e, 0xd3, 0x4e,
	0x10, 0xc6, 0xe5, 0xb4, 0xc9, 0xbf, 0x99, 0xa6, 0xfd, 0xa7, 0x2b, 0x90, 0x4c, 0x05, 0x52, 0x64,
	0xa1, 0x28, 0x97, 0x26, 0x50, 0x2e, 0xa8, 0x07, 0xa4, 0x36, 0x20, 0x41, 0xa5, 0x52, 0xe4, 0x22,
	0x0e, 0x5c, 0xa2, 0x8d, 0x3d, 0xb1, 0x57, 0xb5, 0x77, 0xcd, 0xec, 0xb8, 0xc8, 0x8f, 0xc3, 0x13,
	0xf0, 0x16, 0x3c, 0x17, 0xb2, 0xd7, 0x4d, 0x5a, 0x0a, 0xb7, 0xf9, 0xbe, 0xef, 0xb7, 0x99, 0x99,
	0xec, 0x1a, 0x0e, 0x23, 0x93, 0xe7, 0x46, 0xcf, 0x22, 0xa3, 0x57, 0x2a, 0x29, 0x49, 0xb2, 0x32,
	0x7a, 0x5a, 0x90, 0x61, 0x23, 0x7a, 0x2e, 0x0b, 0xc6, 0x30, 0x7c, 0x2f, 0x6d, 0xaa, 0x74, 0x72,
	0x9a, 0x25, 0x86, 0x14, 0xa7, 0xb9, 0x10, 0xb0, 0xad, 0x65, 0x8e, 0xbe, 0x37, 0xf2, 0x26, 0xfd,
	0xb0, 0xa9, 0x83, 0x97, 0xf0, 0xe4, 0x2c, 0x33, 0xd1, 0xf5, 0x5b, 0xc9, 0xb2, 0x3d, 0x70, 0xc5,
	0x54, 0x46, 0x5c, 0x12, 0x8a, 0x47, 0xd0, 0xfd, 0xae, 0x62, 0x4e, 0x9b, 0x13, 0x7b, 0xa1, 0x13,
	0xc1, 0x0b, 0x18, 0x5e, 0x52, 0x8c, 0x84, 0x74, 0x1a, 0xc7, 0x84, 0xd6, 0xa2, 0x15, 0x4f, 0xa1,
	0x2f, 0x6f, 0x85, 0xef, 0x8d, 0xb6, 0x26, 0xfd, 0x70, 0x63, 0x04, 0xbf, 0x3c, 0xe8, 0xcf, 0x8d,
	0xb6, 0xa8, 0x19, 0x49, 0xec, 0x43, 0x47, 0xc5, 0xed, 0x4f, 0x76, 0x54, 0x5c, 0x8f, 0x95, 0x1a,
	0xcb, 0x7e, 0xc7, 0x8d, 0x55, 0xd7, 0xb5, 0x57, 0x18, 0x62, 0x7f, 0xab, 0xa1, 0x9a, 0x5a, 0x3c,
	0x86, 0x5e, 0x6e, 0x8b, 0x85, 0x8a, 0xfd, 0xed, 0x86, 0xec, 0xe6, 0xb6, 0xf8, 0x10, 0x8b, 0x43,
	0xd8, 0x51, 0x31, 0x6a, 0x56, 0x5c, 0xf9, 0xdd, 0x91, 0x37, 0x19, 0x84, 0x6b, 0x2d, 0xc6, 0xf0,
	0x7f, 0x94, 0x29, 0xd4, 0xbc, 0xe0, 0xcc, 0x2e, 0x22, 0x24, 0xf6, 0x7b, 0x0d, 0xb2, 0xe7, 0xec,
	0xcf, 0x99, 0x9d, 0x23, 0x71, 0xcd, 0x59, 0xa4, 0x1b, 0xa4, 0x0d, 0xf7, 0x9f, 0xe3, 0x9c, 0xdd,
	0x72, 0xc1, 0x39, 0xec, 0xb4, 0xab, 0x5b, 0xf1, 0x06, 0x0e, 0xa2, 0xdb, 0x9d, 0x16, 0xb9, 0x2c,
	0x0a, 0xa5, 0x93, 0x66, 0xf5, 0xdd, 0xe3, 0x83, 0xa9, 0xbb, 0x85, 0xe9, 0x7a, 0xe9, 0x70, 0xb8,
	0x66, 0x2f, 0x1c, 0x1a, 0x8c, 0x00, 0xea, 0xd8, 0x10, 0xab, 0xf2, 0xef, 0x77, 0xf3, 0xd3, 0x83,
	0xc1, 0x5c, 0x16, 0x72, 0xa9, 0x32, 0xc5, 0x0a, 0xad, 0x38, 0x87, 0x41, 0x74, 0x47, 0xb7, 0xdd,
	0xc6, 0xeb, 0x6e, 0x77, 0xb2, 0x7b, 0xe2, 0x9d, 0x66, 0xaa, 0xc2, 0x7b, 0x67, 0x0f, 0xaf, 0xe0,
	0xe0, 0x01, 0x22, 0x86, 0xb0, 0x75, 0x8d, 0x55, 0x3b, 0x44, 0x5d, 0x8a, 0x09, 0x74, 0x6f, 0x64,
	0x56, 0x62, 0x73, 0x3b, 0xbb, 0xc7, 0xe2, 0x41, 0xaf, 0x2a, 0x74, 0xc0, 0x49, 0xe7, 0xb5, 0x17,
	0x0c, 0x00, 0x36, 0x41, 0xf0, 0xc3, 0x83, 0x67, 0xa7, 0xcc, 0x68, 0xb9, 0x79, 0xa1, 0xf3, 0x14,
	0xa3, 0x6b, 0xa5, 0x93, 0x4f, 0x92, 0x64, 0x8e, 0x5c, 0xff, 0x87, 0x63, 0xd8, 0x47, 0x2d, 0x97,
	0x19, 0xde, 0x66, 0x4d, 0xeb, 0x9d, 0xf0, 0x0f, 0x57, 0x9c, 0x80, 0x4f, 0xf8, 0xad, 0x54, 0x84,
	0xf1, 0xc7, 0x32, 0x5f, 0x22, 0x5d, 0xae, 0x2e, 0xd0, 0x5a, 0x99, 0xa0, 0x6d, 0x06, 0xdb, 0x0b,
	0xff, 0x99, 0xd7, 0x4f, 0x73, 0x55, 0x87, 0xa8, 0xa3, 0xaa, 0x7d, 0x4f, 0x1b, 0xe3, 0xec, 0x0b,
	0x3c, 0x37, 0x94, 0x4c, 0xd3, 0xaa, 0x40, 0xca, 0x30, 0x4e, 0x90, 0xa6, 0x2b, 0xb9, 0x24, 0x15,
	0xb9, 0xef, 0xc9, 0xb6, 0xfb, 0x7e, 0x9d, 0x26, 0x8a, 0xd3, 0x72, 0x59, 0xcb, 0xd9, 0x1d, 0x78,
	0xe6, 0xe0, 0x23, 0x07, 0x1f, 0x25, 0x66, 0xe6, 0xf8, 0x65, 0xaf, 0x71, 0x5e, 0xfd, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x81, 0xfa, 0xa3, 0x85, 0xac, 0x03, 0x00, 0x00,
}
